Hotel/Models/BookingModel.cs
using System.ComponentModel.DataAnnotations;

namespace Hotel.Models
{
    public class BookingModel
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "name")]
        [MinLength(10, ErrorMessage ="the miniumm length is 10 characters"),MaxLength(70,ErrorMessage = "the maxiumm length is 70 characters")]
        public string Name { get; set; }
        [Display(Name = "select RoomType")]
        public string RoomType { get; set; }
        [Display(Name = "TotalMembers")]
        public int TotalMembers { get; set; }
        public DateTime Date { get; set; }
        [Display(Name = "ArrivalDate")]
        public DateTime ArrivalDate { get; set; }
        [Display(Name = "DepatureDate")]
        public DateTime DepatureDate { get; set; }
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Display(Name = "PhoneNumber")]
        public int Phone { get; set; }

    }
}

Hotel/Models/CustomerModel.cs
using System.ComponentModel.DataAnnotations;

namespace Hotel.Models
{
    public class CustomerModel
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "name")]
        public string Name { get; set; }
        [Display(Name = "RoomType")]
        public string RoomType { get; set; }
        [Display(Name = "TotalMembers")]
        public int TotalMembers { get; set; }
        public DateTime Date { get; set; }
        [Display(Name = "Age")]
        public int Age { get; set; }
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Display(Name = "PhoneNumber")]
        public int Phone { get; set; }


    }
}

Hotel/Models/EmployeeModel.cs
using System.ComponentModel.DataAnnotations;

namespace Hotel.Models
{
    public class EmployeeModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Required]
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        [Display(Name = "Email")]
        [Required]
        public string Email { get; set; }
        [Display(Name = "PhoneNumber")]
        [Required]
        public int Phone { get; set; }
        [Display(Name = "Date")]
        [Required]
        public DateTime Date { get; set; } = DateTime.Now;

        [Display(Name = "Password")]
        [Required]
        public int Password { get; set; }
        [Display(Name = "Confirm Password")]
        [Required]
        public int ConfirmPassword { get; set; }
        [Display(Name = "Salary")]
        [Required]
        public int Salary { get; set; }

    }
}

Hotel/Models/ErrorViewModel.cs
namespace Hotel.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hotel/Models/PayrollModel.cs
namespace Hotel.Models
{
    public class PayrollModel
    {
    }
}

Hotel/Models/RoomModel.cs
using System.ComponentModel.DataAnnotations;

namespace Hotel.Models
{
    public class RoomModel

    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "RoomNumber")]
        public int RoomNumber { get; set; }
        [Required]
        [Display(Name = "RoomType")]
        public string RoomType { get; set; }
        [Required]
        public int Active { get; set; }
        [Display(Name = "BadCont")]
        [Required]
        public int BadCont { get; set; }
        [Display(Name = "Rent")]
        [Required]
        public int Rent { get; set; }
        [Display(Name = "PhoneNumber")]
        [Required]
        public int Phone { get; set; }


    }
}

Hotel/Models/StaffModel.cs
using System.ComponentModel.DataAnnotations;

namespace Hotel.Models
{
    public class StaffModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Required]
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        [Display(Name = "Email")]
        [Required]
        public string Email { get; set; }
        [Display(Name = "PhoneNumber")]
        [Required]
        public int Phone { get; set; }
        [Display(Name = "Date")]
        [Required]
        public DateTime Date { get; set; } = DateTime.Now;

        [Display(Name = "Password")]
        [Required]
        public int Password { get; set; }
        [Display(Name = "Confirm Password")]
        [Required]
        public int ConfirmPassword { get; set; }
        [Display(Name = "Salary")]
        [Required]
        public int Salary { get; set; }




    }
}

Hotel/Controllers/BookingController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel.Controllers
{
    public class BookingController : Controller
    {
        public IActionResult bookingList()
        {
            return View();
        }  
        public IActionResult EditBooking()
        {
            return View();
        }  
        public IActionResult AddBooking()
        {
            return View();
        }
    }
}

Hotel/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel.Controllers
{
    public class CustomerController : Controller
    {
        public IActionResult CustomerList()
        {
            return View();
        }
        public IActionResult AddCustomer()
        {
            return View();
        }  
        public IActionResult EditCustomer()
        {
            return View();
        }
    }
}

Hotel/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult AddEmployee()
        {
            return View();
        }
        public IActionResult EmployeeList()
        {
            return View();
        }
        public IActionResult Holyday ()
        {
            return View();
        }
        public IActionResult Leave()
        {
            return View();
        }
    }
}

Hotel/Controllers/HomeController.cs
using Hotel.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Hotel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hotel/Controllers/PayrollController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel.Controllers
{
    public class PayrollController : Controller
    {
        public IActionResult EmployeeSalary()
        {
            return View();
        } 
        public IActionResult Payslip()
        {
            return View();
        }  
        public IActionResult AddSalary()
        {
            return View();
        }
    }
}

Hotel/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel.Controllers
{
    public class RoomsController : Controller
    {
        public IActionResult RoomList()
        {
            return View();
        }  
        public IActionResult AddRoom()
        {
            return View();
        } 
        public IActionResult EditRoom()
        {
            return View();
        }
    }
}

Hotel/Controllers/StaffController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel.Controllers
{
    public class StaffController : Controller
    {
        public IActionResult StaffList()
        {
            return View();
        }
        public IActionResult EditStaff()
        {
            return View();
        }
        public IActionResult AddStaff()
        {
            return View();
        }
    }
}

Hotel/Views/Booking/Addbooking.cshtml
<div class="content container-fluid">
				<div class="page-header">
					<div class="row align-items-center">
						<div class="col">
							<h3 class="page-title mt-5">Add Booking</h3> </div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<form>
							<div class="row formtype">
								
								<div class="col-md-4">
									<div class="form-group">
										<label>Name</label>
										<input class="form-control" id="sel1" name="sellist1">
											
										
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Room Type</label>
										<select class="form-control" id="sel2" name="sellist1">
											<option>Select</option>
											<option>Single</option>
											<option>Double</option>
											<option>Quad</option>
											<option>King</option>
											<option>Suite</option>
											<option>Villa</option>
										</select>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Total Members</label>
										<select class="form-control" id="sel3" name="sellist1">
											<option>Select</option>
											<option>1</option>
											<option>2</option>
											<option>3</option>
											<option>4</option>
											<option>5</option>
										</select>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Date</label>
										<div class="cal-icon">
											<input type="text" class="form-control datetimepicker"> </div>
									</div>
								</div>
								
								
								<div class="col-md-4">
									<div class="form-group">
										<label>Arrival Date</label>
										<div class="cal-icon">
											<input type="text" class="form-control datetimepicker"> </div>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Depature Date</label>
										<div class="cal-icon">
											<input type="text" class="form-control datetimepicker"> </div>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Email ID</label>
										<input type="text" class="form-control" id="usr"> </div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Phone Number</label>
										<input type="text" class="form-control" id="usr1"> </div>
								</div>
								
							
							
							</div>
						</form>
					</div>
				</div>
				<button type="button" class="btn btn-primary buttonedit1">Create Booking</button>
			</div>

Hotel/Views/Customer/AddCustomer.cshtml
<div class="content container-fluid">
				<div class="page-header">
					<div class="row align-items-center">
						<div class="col">
							<h3 class="page-title mt-5">Add Customer</h3> </div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<form>
								<div class="row formtype">
								<div class="col-md-4">
									<div class="form-group">
										<label>Name</label>
										<input class="form-control" id="sel1" name="sellist1">
										</div>
								
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Room Type</label>
										<select class="form-control" id="sel2" name="sellist1">
											<option>select_Gender</option>
											<option>Male</option>
											<option>Female</option>
											
										
										</select>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Total Members</label>
										<select class="form-control" id="sel3" name="sellist1">
											<option>Select</option>
											<option>1</option>
											<option>2</option>
											<option>3</option>
											<option>4</option>
											<option>5</option>
										</select>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Date</label>
										<div class="cal-icon">
											<input type="text" class="form-control datetimepicker"> </div>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Age</label>
										<div class="time-icon">
											<input type="text" class="form-control" id="datetimepicker3"> </div>
									</div>
								</div>
								
								
								<div class="col-md-4">
									<div class="form-group">
										<label>Email ID</label>
										<input type="text" class="form-control" id="usr"> </div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Phone Number</label>
										<input type="text" class="form-control" id="usr1"> </div>
								</div>
							
								
								
							</div>
						</form>
					</div>
				</div>
				<button type="button" class="btn btn-primary buttonedit1">Create Customer</button>
			</div>

Hotel/Views/Employee/EmployeeList.cshtml
<div class="content container-fluid">
<div class="page-header">
<div class="row align-items-center">
<div class="col">
<div class="mt-5">
<h4 class="card-title float-left mt-2">Employee</h4>
<a asp-action ="AddEmployee" asp-controller="Employee" class="btn btn-primary float-right veiwbutton">Add Employee</a>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-lg-12">
<form>  
<div class="row formtype">
<div class="col-md-3">
<div class="form-group">
<label>Employee ID</label>
<input type="text" class="form-control" id="usr">
</div>
</div> <div class="col-md-3">
<div class="form-group">
<label>Employee Name</label>
<input type="text" class="form-control" id="usr1">
</div>
</div>
<div class="col-md-3">
<div class="form-group">
<label>Role</label>
<select class="form-control" id="sel1" name="sellist1">
<option>Admin</option>
<option>Manager</option>
<option>Staff</option>
<option>Accountant</option>
</select>
</div>
</div>
<div class="col-md-3">
<div class="form-group">
<label>Search</label>
<a href="#" class="btn btn-success btn-block mt-0 search_button"> Search </a>

</div>
</div>
</div>
</form>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div class="card">
<div class="card-body">
<div class="table-responsive">
<table class="datatable table table-stripped">
<thead>
<tr>
<th>Name</th>
<th>Employee ID</th>
<th>Email</th>
<th>Mobile</th>
<th>Join Date</th>
<th>role</th>
<th class="text-right">Actions</th>
</tr>
</thead>
<tbody>
<tr>
<td>Albina Simonis</td>
<td>Ma-0001</td>
<td><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="b7d6dbd5ded9d6c4dedad8d9dec4f7d2cfd6dac7dbd299d4d8da">[email&#160;protected]</a></td>
<td>828-634-2744</td>
<td>7 May 2015</td>
<td>
<span class="custom-badge status-green">Manager</span>
</td>
<td class="text-right">
<div class="dropdown dropdown-action">
<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-v ellipse_color"></i></a>
<div class="dropdown-menu dropdown-menu-right">
<a class="dropdown-item" href="edit-employee.html"><i class="fas fa-pencil-alt m-r-5"></i> Edit</a>
<a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete_asset"><i class="fas fa-trash-alt m-r-5"></i> Delete</a>
</div>
</div>
</td>
</tr>
<tr>
<td>Cristina Groves</td>
<td>SF-0001</td>
<td><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="680b1a011b1c0106090f1a071e0d1b280d10090518040d460b0705">[email&#160;protected]</a></td>
<td>928-344-5176</td>
<td>1 Jan 2013</td>
<td>Staff</td>
<td class="text-right">
<div class="dropdown dropdown-action">
<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-v ellipse_color"></i></a>
<div class="dropdown-menu dropdown-menu-right">
<a class="dropdown-item" href="edit-employee.html"><i class="fas fa-pencil-alt m-r-5"></i> Edit</a>
<a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete_asset"><i class="fas fa-trash-alt m-r-5"></i> Delete</a>
</div>
</div>
</td>
</tr>
<tr>
<td>Mary Mericle</td>
<td>SF-0003</td>
<td><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="4825293a31252d3a212b242d082d30292538242d662b2725">[email&#160;protected]</a></td>
<td>603-831-4983</td>
<td>27 Dec 2017</td>
<td>Accountant</td>
<td class="text-right">
<div class="dropdown dropdown-action">
<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-v ellipse_color"></i></a>
<div class="dropdown-menu dropdown-menu-right">
<a class="dropdown-item" href="edit-employee.html"><i class="fas fa-pencil-alt m-r-5"></i> Edit</a>
<a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete_asset"><i class="fas fa-trash-alt m-r-5"></i> Delete</a>
</div>
</div>
</td>
</tr>
<tr>
<td>Haylie Feeney</td>
<td>SF-0002</td>
<td><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="4f272e3623262a292a2a212a360f2a372e223f232a612c2022">[email&#160;protected]</a></td>
<td>616-774-4962</td>
<td>21 Apr 2017</td>
<td>Room Maintainers</td>
<td class="text-right">
<div class="dropdown dropdown-action">
<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-v ellipse_color"></i></a>
<div class="dropdown-menu dropdown-menu-right">
<a class="dropdown-item" href="edit-employee.html"><i class="fas fa-pencil-alt m-r-5"></i> Edit</a>
<a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete_asset"><i class="fas fa-trash-alt m-r-5"></i> Delete</a>
</div>
</div>
</td>
</tr>
<tr>
<td>Zoe Butler</td>
<td>SF-0001</td>
<td><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="5e24313b3c2b2a323b2c1e3b263f332e323b703d3133">[email&#160;protected]</a></td>
<td>444-555-9999</td>
<td>19 May 2012</td>
<td>Receptionist</td>
<td class="text-right">
<div class="dropdown dropdown-action">
<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-v ellipse_color"></i></a>
<div class="dropdown-menu dropdown-menu-right">
<a class="dropdown-item" href="edit-employee.html"><i class="fas fa-pencil-alt m-r-5"></i> Edit</a>
<a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete_asset"><i class="fas fa-trash-alt m-r-5"></i> Delete</a>
</div>
</div>
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<div id="delete_asset" class="modal fade delete-modal" role="dialog">
<div class="modal-dialog modal-dialog-centered">
<div class="modal-content">
<div class="modal-body text-center">
<img src="assets/img/sent.png" alt="" width="50" height="46">
<h3 class="delete_class">Are you sure want to delete this Asset?</h3>
<div class="m-t-20"> <a href="#" class="btn btn-white" data-dismiss="modal">Close</a>
<button type="submit" class="btn btn-danger">Delete</button>
</div>
</div>
</div>
</div>
</div>
</div>

Hotel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
	<title>@ViewData["Title"];</title>
	<link rel="shortcut icon" type="~/image/x-icon" href="~/assets/img/favicon.png">
	<link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/assets/plugins/fontawesome/css/fontawesome.min.css">
	<link rel="stylesheet" href="~/assets/plugins/fontawesome/css/all.min.css">
	<link rel="stylesheet" href="~/assets/css/feathericon.min.css">
	<link rel="stylesheet" href="~/assets/plugins/datatables/datatables.min.css">
	<link rel="stylesheet" href="~/assets/plugins/morris/morris.css">
	<link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap-datetimepicker.min.css">
	<link rel="stylesheet" href="~/assets/css/style.css"> </head>

<body>
	<div class="main-wrapper">
		<div class="header">
			<div class="header-left">
				<a href="index.html" class="logo"> <img src="~/assets/img/hotel_logo.png" width="50" height="70" alt="logo"> <span class="logoclass">HOTEL</span> </a>
				<a href="index.html" class="logo logo-small"> <img src="~/assets/img/hotel_logo.png" alt="Logo" width="30" height="30"> </a>
			</div>
			

			<a href="javascript:void(0);" id="toggle_btn"> <i class="fe fe-text-align-left"></i> </a>
			<a class="mobile_btn" id="mobile_btn"> <i class="fas fa-bars"></i> </a>
			<ul class="nav user-menu">
				<li class="nav-item dropdown noti-dropdown">
					<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"> <i class="fe fe-bell"></i> <span class="badge badge-pill">3</span> </a>
					<div class="dropdown-menu notifications">
						<div class="topnav-dropdown-header"> <span class="notification-title">Notifications</span> <a href="javascript:void(0)" class="clear-noti"> Clear All </a> </div>
						<div class="noti-content">
							<ul class="notification-list">
								<li class="notification-message">
									<a href="#">
										<div class="media"> <span class="avatar avatar-sm">
											<img class="avatar-img rounded-circle" alt="User Image" src="~/assets/img/profiles/avatar-02.jpg">
											</span>
											<div class="media-body">
												<p class="noti-details"><span class="noti-title">Carlson Tech</span> has approved <span class="noti-title">your estimate</span></p>
												<p class="noti-time"><span class="notification-time">4 mins ago</span> </p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="#">
										<div class="media"> <span class="avatar avatar-sm">
											<img class="avatar-img rounded-circle" alt="User Image" src="~/assets/img/profiles/avatar-11.jpg">
											</span>
											<div class="media-body">
												<p class="noti-details"><span class="noti-title">International Software
													Inc</span> has sent you a invoice in the amount of <span class="noti-title">$218</span></p>
												<p class="noti-time"><span class="notification-time">6 mins ago</span> </p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="#">
										<div class="media"> <span class="avatar avatar-sm">
											<img class="avatar-img rounded-circle" alt="User Image" src="~/assets/img/profiles/avatar-17.jpg">
											</span>
											<div class="media-body">
												<p class="noti-details"><span class="noti-title">John Hendry</span> sent a cancellation request <span class="noti-title">Apple iPhone
													XR</span></p>
												<p class="noti-time"><span class="notification-time">8 mins ago</span> </p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="#">
										<div class="media"> <span class="avatar avatar-sm">
											<img class="avatar-img rounded-circle" alt="User Image" src="~/assets/img/profiles/avatar-13.jpg">
											</span>
											<div class="media-body">
												<p class="noti-details"><span class="noti-title">Mercury Software
													Inc</span> added a new product <span class="noti-title">Apple
													MacBook Pro</span></p>
												<p class="noti-time"><span class="notification-time">12 mins ago</span> </p>
											</div>
										</div>
									</a>
								</li>
							</ul>
						</div>
						<div class="topnav-dropdown-footer"> <a href="#">View all Notifications</a> </div>
					</div>
				</li>
				<li class="nav-item dropdown has-arrow">
					<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"> <span class="user-img"><img class="rounded-circle" src="~/assets/img/profiles/avatar-01.jpg" width="31" alt="Soeng Souy"></span> </a>
					<div class="dropdown-menu">
						<div class="user-header">
							<div class="avatar avatar-sm"> <img src="~/assets/img/profiles/avatar-01.jpg" alt="User Image" class="avatar-img rounded-circle"> </div>
							<div class="user-text">
								<h6>Soeng Souy</h6>
								<p class="text-muted mb-0">Administrator</p>
							</div>
						</div> <a class="dropdown-item" href="profile.html">My Profile</a> <a class="dropdown-item" href="settings.html">Account Settings</a> <a class="dropdown-item" href="login.html">Logout</a> </div>
				</li>
			</ul>
		</div>
		<div class="sidebar" id="sidebar">
			<div class="sidebar-inner slimscroll">
				<div id="sidebar-menu" class="sidebar-menu">
					<ul>
						<li> <a asp-ction="Index" asp-controller="Home"><i class="fas fa-tachometer-alt"></i> <span>Dashboard</span></a> </li>
						<li class="list-divider"></li>
						<li class="submenu"> <a href="#"><i class="fas fa-suitcase"></i> <span> Booking </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a asp-action="bookingList" asp-controller="Booking"> All Booking </a></li>
								<li><a asp-action="EditBooking" asp-controller="Booking"> Edit Booking </a></li>
								<li><a asp-action="Addbooking" asp-controller="Booking"> Add Booking </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-user"></i> <span> Customers </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a asp-action="CustomerList" asp-controller="Customer"> All customers </a></li>
								<li><a asp-action="EditCustomer" asp-controller="Customer"> Edit Customer </a></li>
								<li><a asp-action="AddCustomer" asp-controller="Customer"> Add Customer </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-key"></i> <span> Rooms </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a asp-action="RoomList" asp-controller="Rooms"> All Rooms </a></li>
								<li><a asp-action="EditRoom" asp-controller="Rooms"> Edit Rooms </a></li>
								<li><a asp-action="AddRoom" asp-controller="Rooms"> Add Rooms </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-user"></i> <span> Staff </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a asp-action="StaffList" asp-controller="Staff"> All Staff </a></li>
								<li><a asp-action="AddStaff" asp-controller="Staff"> Add Staff </a></li>
								<li><a asp-action="EditStaff" asp-controller="Staff"> Edit Staff </a></li>
							</ul>
						</li>
						
						
						<li class="submenu"> <a href="#"><i class="fas fa-user"></i> <span> Employees </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a asp-action="EmployeeList" asp-controller="Employee">Employees List </a></li>
								<li><a asp-action="Leave" asp-controller="Employee">Leaves </a></li>
								<li><a asp-action="Holyday" asp-controller="Employee">Holidays </a></li>
								
							</ul>
						</li>
											<li class="submenu"> <a href="#"><i class="fas fa-book"></i> <span> Payroll </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a asp-action= "EmployeeSalary" asp-controller= "Payroll"> Employee Salary </a></li>
								<li><a asp-action= "Payslip" asp-controller= "Payroll">Payslip </a></li>
							</ul>
						</li>
					
											</ul>
				</div>
			</div>
		</div>
		<div class="page-wrapper">
			
		@RenderBody()
		</div>
		<script data-cfasync="false" src="../../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
	<script src="~/assets/js/jquery-3.5.1.min.js"></script>
	<script src="~/assets/js/popper.min.js"></script>
	<script src="~/assets/js/bootstrap.min.js"></script>
	<script src="~/assets/plugins/slimscroll/jquery.slimscroll.min.js"></script>
	<script src="~/assets/plugins/raphael/raphael.min.js"></script>
	<script src="~/assets/plugins/morris/morris.min.js"></script>
	<script src="~/assets/js/chart.morris.js"></script>
	<script src="~/assets/js/script.js"></script>
	<script>
		$(function () {
			$('#datetimepicker3').datetimepicker({
				format: 'LT'

			});
		});
	</script>
</body>

</html>